
[device]
adapter = hci0
mac_addr = 7022A9A9-26B5-9347-99B0-798768AB6434. # updated
alias = BT-TH-6A63F9D9 # updated
type = RNG_BATT # updated
device_id = 255 # modify if hub mode or daisy chain (see readme)

[data]
enable_polling = false # periodically read data
poll_interval = 60 # read data interval (seconds)
temperature_unit = C # F = Fahrenheit, C = Celsius
fields = # fields to log (comma separated), leave empty for all fields

[remote_logging]
enabled = false
url = https://example.com/post.php
auth_header = auth_header # optional HTTP header sent as "Authorization: Bearer <AUTH_HEADER>"

[mqtt]
enabled = false
server = 192.168.0.16
port = 1883
topic = solar/state
user =
password =

[pvoutput]
# free accounts has a cap of max one request per minute.
enabled = false
api_key =
system_id =
